# Generated by Django 5.2.5 on 2025-09-25 10:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bonus',
            name='COMM',
            field=models.DecimalField(decimal_places=5, max_digits=5),
        ),
        migrations.AlterField(
            model_name='bonus',
            name='SAL',
            field=models.DecimalField(decimal_places=5, max_digits=5),
        ),
        migrations.AlterField(
            model_name='emp',
            name='COMM',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='emp',
            name='MGR',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.emp'),
        ),
    ]
