# Generated by Django 5.2.5 on 2025-10-13 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_bonus_comm_alter_bonus_sal_alter_emp_comm_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bonus',
            name='COMM',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='bonus',
            name='SAL',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='emp',
            name='COMM',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='emp',
            name='SAL',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
