# Generated by Django 5.2.5 on 2025-09-24 10:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Countries',
            fields=[
                ('countries_id', models.IntegerField(primary_key=True, serialize=False)),
                ('Countries_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Capitals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('url', models.URLField()),
                ('Countries_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.countries')),
            ],
        ),
    ]
